package com.example.laboratorinis.mybatis.model;

import java.util.List;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.NATIONALITY
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public Long getId() {
        System.out.println("hello");
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setId(Long id) {
        System.out.println("hello from setter");
        System.out.println(id);this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @return the value of PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @param name the value for PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.NATIONALITY
     *
     * @return the value of PUBLIC.AUTHOR.NATIONALITY
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.NATIONALITY
     *
     * @param nationality the value for PUBLIC.AUTHOR.NATIONALITY
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.SURNAME
     *
     * @return the value of PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.SURNAME
     *
     * @param surname the value for PUBLIC.AUTHOR.SURNAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }


    private List<Song> songs;

    public List<Song> getSongs() {
        return songs;
    }

    public void setSongs(List<Song> songs) {
        this.songs = songs;
    }
}