package com.example.laboratorinis.mybatis.model;


import java.util.ArrayList;
import java.util.List;

public class Playlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYLIST.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYLIST.DESCRIPTION
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYLIST.NAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYLIST.ID
     *
     * @return the value of PUBLIC.PLAYLIST.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYLIST.ID
     *
     * @param id the value for PUBLIC.PLAYLIST.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYLIST.DESCRIPTION
     *
     * @return the value of PUBLIC.PLAYLIST.DESCRIPTION
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYLIST.DESCRIPTION
     *
     * @param description the value for PUBLIC.PLAYLIST.DESCRIPTION
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYLIST.NAME
     *
     * @return the value of PUBLIC.PLAYLIST.NAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYLIST.NAME
     *
     * @param name the value for PUBLIC.PLAYLIST.NAME
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    private List<Song> songs = new ArrayList<>();

    public List<Song> getSongs() {
        return songs;
    }

    public void setSongs(List<Song> songs) {
        this.songs = songs;
    }
}