package com.example.laboratorinis.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.AUTHOR_ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    private Long authorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ID
     *
     * @return the value of PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ID
     *
     * @param id the value for PUBLIC.SONG.ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.TITLE
     *
     * @return the value of PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.TITLE
     *
     * @param title the value for PUBLIC.SONG.TITLE
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.AUTHOR_ID
     *
     * @return the value of PUBLIC.SONG.AUTHOR_ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.AUTHOR_ID
     *
     * @param authorId the value for PUBLIC.SONG.AUTHOR_ID
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    private Author author;

    public Author getAuthor(){return author;}

    public void setAuthor() {this.author = author;}

    private List<Playlist> playlists;

    public List<Playlist> getPlaylists() {return playlists;}
    public void setPlaylists() {this.playlists = playlists;}
}