package com.example.laboratorinis.mybatis.dao;

import java.util.List;

import com.example.laboratorinis.mybatis.model.Playlist;
import com.example.laboratorinis.mybatis.model.Song;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    int insert(Song row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    Song selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    List<Song> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Tue Apr 11 21:21:15 EEST 2023
     */
    int updateByPrimaryKey(Song row);

    List<Song> selectNotInPlaylist(Long id);
    List<Song> selectSongsInPlaylist(Long id);

    List<Playlist> selectPlaylistsForSong(Long id);
}